### ISSUE TITLE
Limit scope of `clean` command

### ISSUE THREAD

**Issue by rdnt** [benchkram/bob#73]
By default `bob clean` should only clean artifacts & build info related to the current bobfile's scope. (Now it clears from all projects).

# Todo

- [x] Add project name to build info 
- [x] Change the `bob clean` behaviour so that it will clean only the artifacts&build info belonging to the current bob file.
- [x] Add flag `-g, --global`  to `bob clean` to allow cleaning the entirety of the cache.
